server:
  port: 6103
  use-forward-headers: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root@1234
    url: jdbc:mysql://localhost:3306/comms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update 
feign:
  client:
    config:
      default:  
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: INFO
    com.advatix: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr( ){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{REQUEST_ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
