server:
  port: 6101

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root@1234
    url: jdbc:mysql://localhost:3306/feed-content?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000
