server:
  port: 8081
  servlet:
    session:
      timeout: -1

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

broker:
  relay:
    host: ${activemq.host:172.31.34.17}
    user: admin
    password: admin
  url: tcp://${activemq.host:172.31.34.17}:61616
  queue: actions.queue
  topic: actions.topic

logging:
  level:
    org.springframework.messaging: debug
