server:
  port: 6102

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: developer
    password: America#123
    url: jdbc:mysql://100.25.220.31:38607/shopify-store?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.advatix: DEBUG
