server:
  port: 6101

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: developer
    password: America#123
    url: jdbc:mysql://100.25.220.31:38607/shopify-store?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.advatix: DEBUG
    com.ppublica: DEBUG
    
ppublica:
  shopify:
    security:
      client:
        client_id: f590a93a9d2c2c3586a1c495549546e5
        client_secret: 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
      cipher:
        password: advatix@123
        scope: read_content,write_content,read_themes,write_themes,read_products,write_products,read_product_listings,read_customers,write_customers,read_orders,write_orders,read_all_orders,write_order_edits,read_draft_orders,write_draft_orders,read_inventory,write_inventory,read_locations,read_script_tags,write_script_tags,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_shipping,write_shipping,read_analytics,read_users,write_users,read_checkouts,write_checkouts,read_reports,write_reports,read_price_rules,write_price_rules,read_discounts,write_discounts,read_marketing_events,write_marketing_events,read_resource_feedbacks,write_resource_feedbacks,read_shopify_payments_payouts,read_shopify_payments_disputes,read_translations,write_translations,read_locales,write_locales
